// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AlsProjects.Models.Workouts;

public partial class WorkoutSessions
{
    public int SessionID { get; set; }

    public DateTime SessionDate { get; set; }

    public virtual ICollection<Workouts> Workouts { get; set; } = new List<Workouts>();
}