// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AlsProjects.Models.Workouts;

public partial class WorkoutJournalContext : DbContext {
    public WorkoutJournalContext(DbContextOptions<WorkoutJournalContext> options)
        : base(options) {
    }

    public virtual DbSet<WorkoutSessions> WorkoutSessions { get; set; }

    public virtual DbSet<WorkoutTypes> WorkoutTypes { get; set; }

    public virtual DbSet<Workouts> Workouts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder) {
        modelBuilder.Entity<WorkoutSessions>(entity => {
            entity.HasKey(e => e.SessionID);

            entity.Property(e => e.SessionDate);

            modelBuilder.Entity<WorkoutTypes>(entity => {
                entity.HasKey(e => e.WorkoutTypeID);

                entity.Property(e => e.ExerciseName)
                    .IsRequired()
                    .HasMaxLength(100);
            });

            modelBuilder.Entity<Workouts>(entity => {
                entity.HasKey(e => e.WorkoutID);

                entity.Property<decimal>(e => e.Weight);

                entity.HasOne(d => d.Session).WithMany(p => p.Workouts)
                    .HasForeignKey(d => d.SessionID)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.WorkoutType).WithMany(p => p.Workouts)
                    .HasForeignKey(d => d.WorkoutTypeID)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            OnModelCreatingPartial(modelBuilder);
        });
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}